require('zepto/src/zepto')
require('zepto/src/ajax')
require('zepto/src/assets')
require('zepto/src/callbacks')
require('zepto/src/data')
require('zepto/src/deferred')
require('zepto/src/detect')
require('zepto/src/event')
require('zepto/src/form')
require('zepto/src/fx')
require('zepto/src/fx_methods')
require('zepto/src/gesture')
require('zepto/src/ie')
require('zepto/src/ios3')
require('zepto/src/selector')
require('zepto/src/stack')
require('zepto/src/touch')

window.$ = window.Zepto